name: Telegram Auto Fetch & Send

on:
  schedule:
    - cron: '30 2 * * *'   # UTC 02:30 -> UTC+8 10:30 (早间)
    - cron: '45 13 * * *'  # UTC 13:45 -> UTC+8 21:45 (晚间)
  workflow_dispatch: {}    # 支持手动触发

jobs:
  fetch_and_send:
    runs-on: ubuntu-latest
    env:
      TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      # 可选自定义市场符号（逗号分隔），如要改在仓库 Secrets 里新建 MARKET_SYMBOLS 或在此处直接写
      # MARKET_SYMBOLS: ^GSPC,^IXIC,^DJI,GC=F,CL=F,USDJPY=X,EURUSD=X
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run summary script
        run: |
          python scripts/send_summary.py
